version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inm5151_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend-network

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    networks:
      - backend-network
    environment:
      FLASK_ENV: development
      MYSQL_HOST: db
      MYSQL_DATABASE: inm5151_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "19006:19006"
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mysql_data:

networks:
  backend-network:
    driver: bridge
