version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "19006:19006"
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend