-- MySQL Script generated by MySQL Workbench
-- Mon Sep 16 20:05:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inm5151_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inm5151_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inm5151_db` DEFAULT CHARACTER SET utf8 ;
USE `inm5151_db` ;

-- -----------------------------------------------------
-- Table `inm5151_db`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inm5151_db`.`type` ;

CREATE TABLE IF NOT EXISTS `inm5151_db`.`type` (
  `id_type` INT NOT NULL AUTO_INCREMENT,
  `name_fr` VARCHAR(100) NULL,
  `name_en` VARCHAR(100) NULL,
  `name_la` VARCHAR(100) NULL,
  PRIMARY KEY (`id_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inm5151_db`.`functional_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inm5151_db`.`functional_group` ;

CREATE TABLE IF NOT EXISTS `inm5151_db`.`functional_group` (
  `id_functional_group` INT NOT NULL AUTO_INCREMENT,
  `group` VARCHAR(2) NULL,
  `description` VARCHAR(250) NULL,
  PRIMARY KEY (`id_functional_group`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inm5151_db`.`family`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inm5151_db`.`family` ;

CREATE TABLE IF NOT EXISTS `inm5151_db`.`family` (
  `id_family` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_family`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inm5151_db`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inm5151_db`.`genre` ;

CREATE TABLE IF NOT EXISTS `inm5151_db`.`genre` (
  `id_genre` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_genre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inm5151_db`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inm5151_db`.`location` ;

CREATE TABLE IF NOT EXISTS `inm5151_db`.`location` (
  `id_location` INT NOT NULL AUTO_INCREMENT,
  `latitude` VARCHAR(45) NOT NULL,
  `longitude` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_location`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inm5151_db`.`tree`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inm5151_db`.`tree` ;

CREATE TABLE IF NOT EXISTS `inm5151_db`.`tree` (
  `id_tree` INT NOT NULL AUTO_INCREMENT,
  `date_plantation` DATE NOT NULL,
  `date_measure` DATE NOT NULL,
  `details_url` VARCHAR(150) NULL,
  `id_type` INT NULL,
  `id_genre` INT NULL,
  `id_family` INT NULL,
  `id_functional_group` INT NULL,
  `id_location` INT NULL,
  PRIMARY KEY (`id_tree`),
  INDEX `fk_tree_type_idx` (`id_type` ASC) INVISIBLE,
  INDEX `fk_tree_genre_idx` (`id_genre` ASC) VISIBLE,
  INDEX `fk_tree_family_idx` (`id_family` ASC) VISIBLE,
  INDEX `fk_tree_functional_group_idx` (`id_functional_group` ASC) VISIBLE,
  INDEX `fk_tree_id_location_idx` (`id_location` ASC) VISIBLE,
  CONSTRAINT `fk_tree_type`
    FOREIGN KEY (`id_type`)
    REFERENCES `inm5151_db`.`type` (`id_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tree_genre`
    FOREIGN KEY (`id_genre`)
    REFERENCES `inm5151_db`.`genre` (`id_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tree_family`
    FOREIGN KEY (`id_family`)
    REFERENCES `inm5151_db`.`family` (`id_family`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tree_functional_group`
    FOREIGN KEY (`id_functional_group`)
    REFERENCES `inm5151_db`.`functional_group` (`id_functional_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tree_id_location`
    FOREIGN KEY (`id_location`)
    REFERENCES `inm5151_db`.`location` (`id_location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS user;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'user' IDENTIFIED BY 'user';

GRANT SELECT ON TABLE `inm5151_db`.* TO 'user';
GRANT SELECT, INSERT, TRIGGER ON TABLE `inm5151_db`.* TO 'user';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `inm5151_db`.* TO 'user';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `inm5151_db`.`type`
-- -----------------------------------------------------
START TRANSACTION;
USE `inm5151_db`;
INSERT INTO `inm5151_db`.`type` (`name_fr`, `name_en`, `name_la`) VALUES ('Catalpa de lOuest', 'Western Catalpa', 'Catalpa speciosa');
INSERT INTO `inm5151_db`.`type` (`name_fr`, `name_en`, `name_la`) VALUES ('Phellodendron de lAmour Maelio', 'Maelio Amur Cork Tree', 'Phellodendron amurensis Maelio');
INSERT INTO `inm5151_db`.`type` (`name_fr`, `name_en`, `name_la`) VALUES ('Érable à Giguère', 'Manitoba Maple', 'Acer negundo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `inm5151_db`.`functional_group`
-- -----------------------------------------------------
START TRANSACTION;
USE `inm5151_db`;
INSERT INTO `inm5151_db`.`functional_group` (`group`, `description`) VALUES ('1A', 'Conifères généralement tolérants à l’ombre, mais pas à la sécheresse ou l’inondation.');
INSERT INTO `inm5151_db`.`functional_group` (`group`, `description`) VALUES ('1B', 'Conifères héliophiles (qui aime la lumière), tolérants à la sécheresse.');
INSERT INTO `inm5151_db`.`functional_group` (`group`, `description`) VALUES ('2A', 'Arbres tolérants à l’ombre à feuilles larges et minces, croissance moyenne. Graines dispersées surtout par le vent.');
INSERT INTO `inm5151_db`.`functional_group` (`group`, `description`) VALUES ('2B', 'Ressemblent au 2A sauf pour les semences très lourdes et dispersées par gravité.');
INSERT INTO `inm5151_db`.`functional_group` (`group`, `description`) VALUES ('2C', 'Grands arbres tolérants à l’inondation.');
INSERT INTO `inm5151_db`.`functional_group` (`group`, `description`) VALUES ('3A', 'Petits arbres tolérants à la sécheresse, bois lourd, feuilles épaisses, croissance faible.');
INSERT INTO `inm5151_db`.`functional_group` (`group`, `description`) VALUES ('3B', 'Groupe « moyen ». Intolérant à l’inondation.');
INSERT INTO `inm5151_db`.`functional_group` (`group`, `description`) VALUES ('4A', 'Grands arbres à semences et bois lourds. Plusieurs tolérants à la sécheresse.');
INSERT INTO `inm5151_db`.`functional_group` (`group`, `description`) VALUES ('4B', 'Grande tolérance à la sécheresse, mais pas à l’ombre ou inondation.');
INSERT INTO `inm5151_db`.`functional_group` (`group`, `description`) VALUES ('5', 'Espèces pionnières à très petites semences. Croissance rapide, tolérants à l’inondation, bois léger.');

COMMIT;


-- -----------------------------------------------------
-- Data for table `inm5151_db`.`family`
-- -----------------------------------------------------
START TRANSACTION;
USE `inm5151_db`;
INSERT INTO `inm5151_db`.`family` (`name`) VALUES ('Sapindaceae');
INSERT INTO `inm5151_db`.`family` (`name`) VALUES ('Juglandaceae');
INSERT INTO `inm5151_db`.`family` (`name`) VALUES ('Malvaceae');
INSERT INTO `inm5151_db`.`family` (`name`) VALUES ('Fagaceae');

COMMIT;


-- -----------------------------------------------------
-- Data for table `inm5151_db`.`genre`
-- -----------------------------------------------------
START TRANSACTION;
USE `inm5151_db`;
INSERT INTO `inm5151_db`.`genre` (`name`) VALUES ('Acer');
INSERT INTO `inm5151_db`.`genre` (`name`) VALUES ('Catalpa');
INSERT INTO `inm5151_db`.`genre` (`name`) VALUES ('Tilia');

COMMIT;


-- -----------------------------------------------------
-- Data for table `inm5151_db`.`location`
-- -----------------------------------------------------
START TRANSACTION;
USE `inm5151_db`;
INSERT INTO `inm5151_db`.`location` (`latitude`, `longitude`) VALUES ('45.72587', '-73.45703');
INSERT INTO `inm5151_db`.`location` (`latitude`, `longitude`) VALUES ('45.77804', '-73.40377');
INSERT INTO `inm5151_db`.`location` (`latitude`, `longitude`) VALUES ('45.7259', '-73.45707');
INSERT INTO `inm5151_db`.`location` (`latitude`, `longitude`) VALUES ('45.73708', '-73.44643');

COMMIT;


-- -----------------------------------------------------
-- Data for table `inm5151_db`.`tree`
-- -----------------------------------------------------
START TRANSACTION;
USE `inm5151_db`;
INSERT INTO `inm5151_db`.`tree` (`date_plantation`, `date_measure`, `details_url`, `id_type`, `id_genre`, `id_family`, `id_functional_group`, `id_location`) VALUES ('2019-07-12', '2021-06-05', 'https://arbres.hydroquebec.com/fiche-arbre-arbuste/4857', 1, 1, 1, 2, 2);
INSERT INTO `inm5151_db`.`tree` (`date_plantation`, `date_measure`, `details_url`, `id_type`, `id_genre`, `id_family`, `id_functional_group`, `id_location`) VALUES ('2018-06-24', '2022-09-16', 'https://arbres.hydroquebec.com/fiche-arbre-arbuste/4552', 2, 2, 2, 5, 1);
INSERT INTO `inm5151_db`.`tree` (`date_plantation`, `date_measure`, `details_url`, `id_type`, `id_genre`, `id_family`, `id_functional_group`, `id_location`) VALUES ('2017-10-12', '2023-01-11', 'https://arbres.hydroquebec.com/fiche-arbre-arbuste/4705', 2, 3, 3, 4, 3);

COMMIT;

