"""migration DB

Revision ID: 2de16e82bd44
Revises: d74129c4abc4
Create Date: 2024-10-15 03:44:04.070216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de16e82bd44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree_hors_rue', schema=None) as batch_op:
        batch_op.drop_constraint('tree_hors_rue_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tree_search', ['no_emp'], ['no_emp'], referent_schema='inm5151_db')

    with op.batch_alter_table('tree_rue', schema=None) as batch_op:
        batch_op.drop_constraint('tree_rue_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tree_search', ['no_emp'], ['no_emp'], referent_schema='inm5151_db')

    with op.batch_alter_table('tree_search', schema=None) as batch_op:
        batch_op.drop_constraint('tree_search_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'nom_tree', ['essence_latin'], ['essence_latin'], referent_schema='inm5151_db')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree_search', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tree_search_ibfk_1', 'nom_tree', ['essence_latin'], ['essence_latin'])

    with op.batch_alter_table('tree_rue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tree_rue_ibfk_1', 'tree_search', ['no_emp'], ['no_emp'])

    with op.batch_alter_table('tree_hors_rue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tree_hors_rue_ibfk_1', 'tree_search', ['no_emp'], ['no_emp'])

    # ### end Alembic commands ###
