"""modifier length password user

Revision ID: 2eb0fdc32f9f
Revises: 0531809c9749
Create Date: 2024-11-02 12:48:22.145938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb0fdc32f9f'
down_revision = '0531809c9749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='inm5151_db'
    )
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tree_family', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_genre', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_id_location', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_type', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_functional_group', type_='foreignkey')
        batch_op.create_foreign_key('fk_tree_id_location', 'location', ['id_location'], ['id_location'], referent_schema='inm5151_db')
        batch_op.create_foreign_key('fk_tree_functional_group', 'functional_group', ['id_functional_group'], ['id_functional_group'], referent_schema='inm5151_db')
        batch_op.create_foreign_key('fk_tree_family', 'family', ['id_family'], ['id_family'], referent_schema='inm5151_db')
        batch_op.create_foreign_key('fk_tree_genre', 'genre', ['id_genre'], ['id_genre'], referent_schema='inm5151_db')
        batch_op.create_foreign_key('fk_tree_type', 'type', ['id_type'], ['id_type'], referent_schema='inm5151_db')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tree_type', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_genre', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_family', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_functional_group', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_id_location', type_='foreignkey')
        batch_op.create_foreign_key('fk_tree_functional_group', 'functional_group', ['id_functional_group'], ['id_functional_group'])
        batch_op.create_foreign_key('fk_tree_type', 'type', ['id_type'], ['id_type'])
        batch_op.create_foreign_key('fk_tree_id_location', 'location', ['id_location'], ['id_location'])
        batch_op.create_foreign_key('fk_tree_genre', 'genre', ['id_genre'], ['id_genre'])
        batch_op.create_foreign_key('fk_tree_family', 'family', ['id_family'], ['id_family'])

    op.drop_table('user', schema='inm5151_db')
    # ### end Alembic commands ###
