"""Ajouter arbre.image_url

Revision ID: a5ea53c69a91
Revises: 14616f283f9e
Create Date: 2024-11-03 01:47:44.502395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ea53c69a91'
down_revision = '14616f283f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=254), nullable=True))
        batch_op.drop_constraint('fk_tree_type', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_family', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_id_location', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_genre', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_functional_group', type_='foreignkey')
        batch_op.create_foreign_key('fk_tree_genre', 'genre', ['id_genre'], ['id_genre'], referent_schema='inm5151_db')
        batch_op.create_foreign_key('fk_tree_type', 'type', ['id_type'], ['id_type'], referent_schema='inm5151_db')
        batch_op.create_foreign_key('fk_tree_id_location', 'location', ['id_location'], ['id_location'], referent_schema='inm5151_db')
        batch_op.create_foreign_key('fk_tree_functional_group', 'functional_group', ['id_functional_group'], ['id_functional_group'], referent_schema='inm5151_db')
        batch_op.create_foreign_key('fk_tree_family', 'family', ['id_family'], ['id_family'], referent_schema='inm5151_db')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tree_family', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_functional_group', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_id_location', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_type', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_genre', type_='foreignkey')
        batch_op.create_foreign_key('fk_tree_functional_group', 'functional_group', ['id_functional_group'], ['id_functional_group'])
        batch_op.create_foreign_key('fk_tree_genre', 'genre', ['id_genre'], ['id_genre'])
        batch_op.create_foreign_key('fk_tree_id_location', 'location', ['id_location'], ['id_location'])
        batch_op.create_foreign_key('fk_tree_family', 'family', ['id_family'], ['id_family'])
        batch_op.create_foreign_key('fk_tree_type', 'type', ['id_type'], ['id_type'])
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
