"""Initial migration

Revision ID: b38d020b3ac8
Revises: 
Create Date: 2024-09-17 21:54:46.851558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38d020b3ac8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('id_family', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id_family'),
    schema='inm5151_db'
    )
    op.create_table('functional_group',
    sa.Column('id_functional_group', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=2), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id_functional_group'),
    schema='inm5151_db'
    )
    op.create_table('genre',
    sa.Column('id_genre', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id_genre'),
    schema='inm5151_db'
    )
    op.create_table('location',
    sa.Column('id_location', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(length=45), nullable=False),
    sa.Column('longitude', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id_location'),
    schema='inm5151_db'
    )
    op.create_table('type',
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('name_fr', sa.String(length=100), nullable=True),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('name_la', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_type'),
    schema='inm5151_db'
    )
    op.create_table('tree',
    sa.Column('id_tree', sa.Integer(), nullable=False),
    sa.Column('date_plantation', sa.Date(), nullable=False),
    sa.Column('date_measure', sa.Date(), nullable=False),
    sa.Column('details_url', sa.String(length=150), nullable=True),
    sa.Column('id_type', sa.Integer(), nullable=True),
    sa.Column('id_genre', sa.Integer(), nullable=True),
    sa.Column('id_family', sa.Integer(), nullable=True),
    sa.Column('id_functional_group', sa.Integer(), nullable=True),
    sa.Column('id_location', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_family'], ['inm5151_db.family.id_family'], name='fk_tree_family'),
    sa.ForeignKeyConstraint(['id_functional_group'], ['inm5151_db.functional_group.id_functional_group'], name='fk_tree_functional_group'),
    sa.ForeignKeyConstraint(['id_genre'], ['inm5151_db.genre.id_genre'], name='fk_tree_genre'),
    sa.ForeignKeyConstraint(['id_location'], ['inm5151_db.location.id_location'], name='fk_tree_id_location'),
    sa.ForeignKeyConstraint(['id_type'], ['inm5151_db.type.id_type'], name='fk_tree_type'),
    sa.PrimaryKeyConstraint('id_tree'),
    schema='inm5151_db'
    )
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.create_index('fk_tree_family_idx', ['id_family'], unique=False)
        batch_op.create_index('fk_tree_functional_group_idx', ['id_functional_group'], unique=False)
        batch_op.create_index('fk_tree_genre_idx', ['id_genre'], unique=False)
        batch_op.create_index('fk_tree_id_location_idx', ['id_location'], unique=False)
        batch_op.create_index('fk_tree_type_idx', ['id_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.drop_index('fk_tree_type_idx')
        batch_op.drop_index('fk_tree_id_location_idx')
        batch_op.drop_index('fk_tree_genre_idx')
        batch_op.drop_index('fk_tree_functional_group_idx')
        batch_op.drop_index('fk_tree_family_idx')

    op.drop_table('tree', schema='inm5151_db')
    op.drop_table('type', schema='inm5151_db')
    op.drop_table('location', schema='inm5151_db')
    op.drop_table('genre', schema='inm5151_db')
    op.drop_table('functional_group', schema='inm5151_db')
    op.drop_table('family', schema='inm5151_db')
    # ### end Alembic commands ###
