"""Mise à jour des champs latitude et longitude avec Numeric(11,8)

Revision ID: d74129c4abc4
Revises: b38d020b3ac8
Create Date: 2024-10-07 19:50:02.505626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74129c4abc4'
down_revision = 'b38d020b3ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tree_type', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_id_location', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_functional_group', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_genre', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_family', type_='foreignkey')
        batch_op.create_foreign_key('fk_tree_type', 'type', ['id_type'], ['id_type'], referent_schema='inm5151_db')
        batch_op.create_foreign_key('fk_tree_genre', 'genre', ['id_genre'], ['id_genre'], referent_schema='inm5151_db')
        batch_op.create_foreign_key('fk_tree_family', 'family', ['id_family'], ['id_family'], referent_schema='inm5151_db')
        batch_op.create_foreign_key('fk_tree_id_location', 'location', ['id_location'], ['id_location'], referent_schema='inm5151_db')
        batch_op.create_foreign_key('fk_tree_functional_group', 'functional_group', ['id_functional_group'], ['id_functional_group'], referent_schema='inm5151_db')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tree_functional_group', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_id_location', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_family', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_genre', type_='foreignkey')
        batch_op.drop_constraint('fk_tree_type', type_='foreignkey')
        batch_op.create_foreign_key('fk_tree_family', 'family', ['id_family'], ['id_family'])
        batch_op.create_foreign_key('fk_tree_genre', 'genre', ['id_genre'], ['id_genre'])
        batch_op.create_foreign_key('fk_tree_functional_group', 'functional_group', ['id_functional_group'], ['id_functional_group'])
        batch_op.create_foreign_key('fk_tree_id_location', 'location', ['id_location'], ['id_location'])
        batch_op.create_foreign_key('fk_tree_type', 'type', ['id_type'], ['id_type'])

    # ### end Alembic commands ###
